runtime: python311

entrypoint: gunicorn -b :$PORT app:app

instance_class: F1  

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://eatsafe_user:bda123@/eatsafe-db?host=/cloudsql/bda-123-457420:us-central1:eatsafe-sql

beta_settings:
  cloud_sql_instances: bda-123-457420:us-central1:eatsafe-sql

